### ISSUE TITLE
What is the output?

### ISSUE THREAD

**Issue by helloCZZ** [Xharlie/pointnerf#10]
Hello authors, thank you very much for your paper and for releasing code!

I am trying to run the script "bash dev_scripts/w_tt_ft/barn_test.sh". Is the final output a 3D model? I was confused.

This is the log file recorded at runtime.

[out.txt](https://github.com/Xharlie/pointnerf/files/8203151/out.txt)

![image](https://user-images.githubusercontent.com/35329753/157177961-c421ff78-29c2-482b-a2de-aa12c0722e75.png)

**Comment by Xharlie** [comment]
it's the score, the output should also include rendered image results in your folder, please check
