### ISSUE TITLE
 what prempl does？

### ISSUE THREAD

**Issue by QiukuZ** [Xharlie/pointnerf#11]
Thanks for your great work! 
I would like to know what premlp(https://github.com/Xharlie/pointnerf/blob/master/models/mvs/mvs_points_model.py line22) does, just turn 63-dimensional input into 32-dimensional? How is the weight of this part set?

**Comment by Xharlie** [comment]
hi, just to compress the point features so that the convergence is faster.

**Comment by QiukuZ** [comment]
Thank you very much for your reply, I will close this issue
