### ISSUE TITLE
Any instruction for our own data preparation?

### ISSUE THREAD

**Issue by samcao416** [Xharlie/pointnerf#12]
Hi there, I followed all of your instructions and now can train from the scratch. However, I met some difficulties when trying point nerf on my own data. I think some more instructions may be needed for data preparation. Thanks a lot!

**Comment by Xharlie** [comment]
hi, I basically follow nsvf for tanks and temples, you can check the dataloaders under data folder, It is extremely straight forward

**Comment by samcao416** [comment]
Sure, thanks a lot!
