### ISSUE TITLE
Generic or per-scene NeRF?

### ISSUE THREAD

**Issue by caiyongqi** [Xharlie/pointnerf#14]
After training on the dtu dataset, is it possible to also render all the test scenes in the dtu dataset without optimizing each scene? So pointnerf also seems to be a **generic** nerf like pixelnerf?
Then after per-scene optimization, can pointnerf get better performance than Nerf trained with multiple views?

**Comment by Xharlie** [comment]
hi, please refer to the experiment section of the paper and also read README about dtu test, thank you!
