### ISSUE TITLE
loss item

### ISSUE THREAD

**Issue by roywithfiringblade** [Xharlie/pointnerf#16]
Thanks for sharing this work. i am a little confused about the loss item. i know that 'coarse_raycolor' is corresponding to L_render in paper, what is 'ray_masked_loss' and 'ray_miss_loss'?
And if i understand correctly, 'zero_one_loss_items' is the L_sparse in paper. but since we already set the neural points as input data and didn't load mvsnet model, can the parameters of mvsnet also be updated? (when i inspect the variable , the only model is "ray_marching") And you set the neural points to nn.parameter to update, any reasons behind it?

**Comment by Xharlie** [comment]
hi the ray_masked_loss is the loss that only apply to the rays which have neural points neighbors, this is the real loss that drive the opitmization,  coarse_raycolor is the ray_masked_loss + rays that hit nothing and have no gradient.     ray_miss_loss is the metric to see whether the ray hit no neural points actually have foreground color. 
please see the "color loss weight", if a loss has weight 0.0, it means it just for better understanding, not for optimization

**Comment by roywithfiringblade** [comment]
thanks for the explanation, can you explain a bit about what is the purpose of parameterizing the neural points?



---Original---
From: "Qiangeng ***@***.***&gt;
Date: Tue, Mar 22, 2022 23:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Xharlie/pointnerf] loss item (Issue #16)




 
hi the ray_masked_loss is the loss that only apply to the rays which have neural points neighbors, this is the real loss that drive the opitmization,  coarse_raycolor is the ray_masked_loss + rays that hit nothing and have no gradient.     ray_miss_loss is the metric to see whether the ray hit no neural points actually have foreground color.
 please see the "color loss weight", if a loss has weight 0.0, it means it just for better understanding, not for optimization

**Comment by roywithfiringblade** [comment]
@Xharlie  Sorry, stille confused about the neural points parameterization, can you reopen the issue?

**Comment by Xharlie** [comment]
hi what do you mean the neural points parameterization, i guess you are confused with the input to compute radiance?  
we use the world coordinate distance, camera coordinate distance and point feature to calculate the contribution from neural point to shading location, then send the weighted sum inter feature to calculate color and density.

**Comment by Xharlie** [comment]
yea, the mvs model is fixed, since later we found using the pretrained mvs model is already good enough

**Comment by roywithfiringblade** [comment]
@Xharlie if the mvs model is already fixed, the confidence of every point should also be unchanged. so how does point pruning works?

**Comment by Xharlie** [comment]
hi, i think you confused point initialization (mvs, etc.) with per-scene optimization, please refer to Fig.3 in the paper.  All the details are in the paper, i have to retype my paper here to answer this question.

**Comment by roywithfiringblade** [comment]
> hi, i think you confused point initialization (mvs, etc.) with per-scene optimization, please refer to Fig.3 in the paper. All the details are in the paper, i have to retype my paper here to answer this question.

Thanks for explanation, i think i have understood that. @Xharlie
