### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by cv-lab-x** [Xharlie/pointnerf#18]
hi, thanks for your great work.
what device do you use to train the model?  I get segmentation fault (core dumped) when i train on p100 using  bash dev_scripts/w_n360/chair.sh  python 3.7.5 pytorch 1.8.1 pycuda 2021.1 torch_scatter2.0.8

**Comment by Xharlie** [comment]
hi, see the discussion @ #1,
