### ISSUE TITLE
Extract  mesh ?

### ISSUE THREAD

**Issue by Gardlin** [Xharlie/pointnerf#2]
Have you provided extracting mesh function?

**Comment by Xharlie** [comment]
Sorry, I haven't tried to extract mesh.

**Comment by Xharlie** [comment]
will update this if mesh extraction is  implemented

**Comment by morsingher** [comment]
Hi @Xharlie and @Gardlin, as a reference you could try to use this script: https://github.com/kwea123/nerf_pl/blob/dev/extract_color_mesh.py. For vanilla NeRF on the truck scene from Tanks & Temples, you should be able to get something like this:
![truck_nerf](https://user-images.githubusercontent.com/36917382/160146397-d1448812-00e8-49e5-8540-98d4404ad354.png)
With a more recent NeRF version, like PointNeRF, I would expect something a bit better.
