### ISSUE TITLE
Why '/ 4'?

### ISSUE THREAD

**Issue by caiyongqi** [Xharlie/pointnerf#20]
Why '/ 4'?
https://github.com/Xharlie/pointnerf/blob/a614e1d15cc8409e14f80c7b3dd0091939fef758/data/nerf_synth360_ft_dataset.py#L393

**Comment by Xharlie** [comment]
hi, mvsnet has a downsampling rate of 4, but in [nerf_synth360_ft_dataset.py], it's not used anyway. please see the dtu dataloader.
