### ISSUE TITLE
ValueError when generate video

### ISSUE THREAD

**Issue by YuhsiHu** [Xharlie/pointnerf#21]
Thank you for your work!
There is a value error when I test the per-scene optimized Point-NeRFs.
For example, run:
`bash dev_scripts/w_n360/chair_test.sh`
![7ZZgYzkIAP](https://user-images.githubusercontent.com/34529345/160962282-2b3de07e-b7f4-42bd-a1e3-aa164e697da8.png)

I checked the line 92 in visualizer.py and find the total_step is not a integer but a string.
![YcqJvls8OJ](https://user-images.githubusercontent.com/34529345/160962392-973e3f4a-35ca-4564-8b99-b85d7cae6b9d.png)
Therefore, the filename cannot be generated and will bring this error because of mismatched variable type. 
You can fix this bug by converting total_step to int.
Thank you for your time.

**Comment by Xharlie** [comment]
hi, in my machine, the total_step is past from the configuration, which is 20000. can please check the value of total_step in your machine and see why it's not an int.

**Comment by OvOtoQAQ** [comment]
thanks for your help, I have the same problem and fix it following your tutorial:)
