### ISSUE TITLE
"No such file or directory"  only for  scannet  scene

### ISSUE THREAD

**Issue by Gardlin** [Xharlie/pointnerf#23]
Hi , when I redownload the code repo and run from scratch ,It still encounters with the problem of "No such file or directory" when I run scene101.sh ,However it works fine if I run from scratch in the dataset of Nerf Synth. Is there some possiblity that I should change some setting for the scannet scene.
https://github.com/Xharlie/pointnerf/issues/7#issuecomment-1060343926

**Comment by Xharlie** [comment]
hi, did you download scannet data files as in README?
    ├── scannet
    │   │   │──scans 
    |   │   │   │──scene0101_04
    |   │   │   │──scene0241_01

**Comment by Gardlin** [comment]
Yes .And when I  parse  the  .sens file and run colmap  I will   get  like  this 
![image](https://user-images.githubusercontent.com/28174084/161685424-fc258676-4968-467f-8381-e651755e1213.png)

**Comment by Xharlie** [comment]
hi, can you use the provided data instead of parsing by yourself? Please find the discrepancy. I cannot debug for you since im not physically in front of your sever. Please check the logic and find which file is missing and whether you have it.
