### ISSUE TITLE
DTU dataset download

### ISSUE THREAD

**Issue by aditya-vora** [Xharlie/pointnerf#24]
Hello, 

Thanks for the awesome work. However, I am not able to download the DTU training dataset from the gdrive link shared in the repo. It seems that the link is dead. Would it be possible for you to reactivate the link?

Thanks,
Aditya Vora

**Comment by aditya-vora** [comment]
https://drive.google.com/file/d/1eDjh-_bxKKnEuz5h-HXS7EDJn59clx6V/view

This is the link which I am mentioning.

**Comment by Xharlie** [comment]
hi, you can use either ours or mvsnet's , please read the README carefully and use our dtu gdrive data instead if you cannot download from their end
