### ISSUE TITLE
Arguments are required --name

### ISSUE THREAD

**Issue by hugobl1** [Xharlie/pointnerf#27]
Hi everyone, 
I have a problem when launching bash scripts like "bash dev_scripts/w_n360/chair.sh", the argument 'name' is not detected and the terminal returns me the error: 
train_ft.py: error: the following arguments are required: --name
Did any of you had the same problem?

**Comment by Xharlie** [comment]
hi, can you please check if you have deleted something? name is a args. you can do git diff, etc.

**Comment by hugobl1** [comment]
Hi, Thanks for your answer !
I just checked, I didn't change anything except adding the checkpoint and data_src folders

**Comment by Xharlie** [comment]
do you have this problem running other scripts? I cannot reproduce it, also in chair.sh, there is a name argument.
my assessment is in your nrCheckpoint  and   nrDataRoot, there is some uncommon character that's not pure english. the script will break due to python

**Comment by Solonets** [comment]
Hi @Xharlie, thank you for your work. It looks like there is a bug in matplotlib: it removes --name argument from sys.argv on import in latest version. I reported this bug to matplotlib (https://github.com/matplotlib/matplotlib/issues/23236). Meanwhile I think it would be a good idea to rename this flag to something else
