### ISSUE TITLE
Why is it slow for Per-scene Optimization?

### ISSUE THREAD

**Issue by ShaoTengLiu** [Xharlie/pointnerf#47]
I run this command to do **Per-scene optimize from scratch**:
`bash dev_scripts/w_n360/lego.sh`

In the paper, the speed should be 2min / 1K iters. However, on my single 2080Ti, it takes 100min / 1K iters. Anyone meets this problem?

**Comment by Xharlie** [comment]
wow  that's really slow, sounds like you are not using GPU at all.

**Comment by lai-pf** [comment]
> 哇，这真的很慢，听起来你根本没有使用 GPU。

我也遇到了这个情况 确保ship文件夹下没有.pth文件后   
运行bash dev_scripts/w_n360/ship.sh从头开始优化 极其缓慢 
代码是需要哪里设置使用GPU吗 还是说现在的速度已经使用了GPU？
期待回复 正在follow您的工作

**Comment by Xharlie** [comment]
i think you guys mistake nerf optimization with MVS. The MVS part can be slow, but it's not even part of point-nerf's original code. You can choose to replace MVS with other methods. 

Please read the code or paper more carefully, maybe print out some part to see which function are consuming the time.
