### ISSUE TITLE
pycuda error?

### ISSUE THREAD

**Issue by yjcaimeow** [Xharlie/pointnerf#5]
Hi @Xharlie @zexxu ,

Could you help me about the following error? 
<img width="1421" alt="截屏2022-03-02 下午3 04 08" src="https://user-images.githubusercontent.com/75470313/156315028-0f280bd7-5381-4d47-bd8e-f2aaa47c8701.png">

**Comment by wing2791** [comment]
I try to run the following command:
bash dev_scripts/ete/dtu_dgt_d012_img0123_conf_color_dir_agg2.sh
I use cuda11.3,the code is source code，I have no idea about this error.
![image](https://user-images.githubusercontent.com/57736699/228120057-a03ce92d-497b-4b18-9831-c780fde94fd6.png)

**Comment by nexuslrf** [comment]
@wing2791  can you try this to see whether it works? #82

**Comment by wing2791** [comment]
@nexuslrf
I have run following command，but it invaild
**bash dev_scripts/ete/dtu_dgt_d012_img0123_conf_color_dir_agg2.sh**
The following command has not been tested because I have not downloaded the model completely, 
**w_n360/lego.sh & dtu_test_inf/inftest_scan1.sh.**
