### ISSUE TITLE
Question about volumetric rendering in the code

### ISSUE THREAD

**Issue by Gymat** [Xharlie/pointnerf#59]
Hi, thank you very much for your great work and for releasing the code! I was confused about the implementation of volumetric rendering in the code.  Concretely, I show the code below. 
Since in the line of 276, ray_dist values which are larger than 2*voxel_size[2] (vsize[2] in the code) are set to voxel_size[2] by line 278. I have tested on the Scannet and TanksandTemple datasets, where the `opt.raydist_mode_unit = 1`, and I find that the all ray_dist values are set to voxel_size[2].

https://github.com/Xharlie/pointnerf/blob/7a2f199de97d0738d73998f84230098c36f85f1f/models/neural_points_volumetric_model.py#L272-L278

If you could tell me why the ray_dist values need to be clamped to voxel_size, that would be great! Thank you!

**Comment by Xharlie** [comment]
hi, since the point nerf only do shading where it is close to the point cloud, the ray_dist could be very big and violate the assumption for discretizing the integration equation in nerf
