### ISSUE TITLE
How to use point cloud as input

### ISSUE THREAD

**Issue by helloCZZ** [Xharlie/pointnerf#6]
Hello authors, thank you very much for your paper and for releasing code! I am very excited about this work.
I have gotten point cloud data in a ply format somehow, how do I use this data as input to point_nerf.  I don't seem to find it in "READEME.md".
![image](https://user-images.githubusercontent.com/35329753/156800927-08f321a4-77a0-4390-a6ff-663688476511.png)

**Comment by Xharlie** [comment]
Sure, I will upload some scripts, basically just set load_points=1, and it will find some colmap points file to read

**Comment by helloCZZ** [comment]
Hello, thanks for the response! I'm looking forward to the new scripts that will be uploaded soon.😀

**Comment by Xharlie** [comment]
colmap scrips and results/checkpoints uploaded
