### ISSUE TITLE
Why you use 1088x640 instead of the original 1920x1080 for Tanks&Temples?

### ISSUE THREAD

**Issue by immortalCO** [Xharlie/pointnerf#62]
Hi,

We evaluated your code on the Tanks&Temples dataset and found that the images outputted by your model have a size (resolution) of 1088x640‬, with a different ratio from the original image size of 1920x1080. It's also shown in [your config file](https://github.com/Xharlie/pointnerf/blob/master/dev_scripts/w_tt_ft/barn.sh#L21) that you manually set it as 1088x640‬.

For Table 9 in your paper, you compared the results with NSVF, and the numbers of NSVF were the same as those in [NSVF paper](https://arxiv.org/pdf/2007.11571.pdf), which also claims that "The image resolution is 1920 × 1080" for Tanks&Temples.

Why did you choose the resolution of 1088x640? Were the metrics in Table 9 in your paper calculated with images with a resolution of 1088x640 or 1920x1080?

Thanks.

**Comment by Xharlie** [comment]
Hi Jukun, we are using 1080Ti by the time and the memory is very small comparing with FB's clusters used by NSVF. 1088x640‬ is the largest limit my gpu can handle.  If the resolution will affect number, I think I can make adjustment by isolating our results as a single table. If you want to compare with us, you can also downsample to 1088x640‬ both gt test view and the generated test view.
