### ISSUE TITLE
use `channel_axis` instead.

### ISSUE THREAD

**Issue by CHenYYff** [Xharlie/pointnerf#63]
Loading model from: /root/miniconda3/lib/python3.8/site-packages/lpips/weights/v0.1/vgg.pth
/root/autodl-tmp/pointnerf/run/../run/evaluate.py:11: FutureWarning: `multichannel` is a deprecated argument name for `structural_similarity`. It will be removed in version 1.0. Please use `channel_axis` instead.
  return structural_similarity(gt, img, win_size=win_size, multichannel=multichannel)

**Comment by Xharlie** [comment]
hi, maybe it is because people have different version of lpips. To retain the best compatibility, it is better to keep the original usage.
